
#Gamerules that are set when a world is loaded
[gamerules]
	#Whether advancements should be announced in chat
	announce_advancements = true
	#Whether command blocks should notify admins when they perform commands
	command_block_output = false
	#Whether the server should skip checking player speed when the player is wearing elytra. Often helps with jittering due to lag in multiplayer
	disable_elytra_movement_check = false
	#Whether raids are disabled
	disable_raids = false
	#Whether the daylight cycle and moon phases progress
	do_daylight_cycle = true
	#Whether entities that are not mobs should have drops
	do_entity_drops = true
	#Whether fire should spread and naturally extinguish
	do_fire_tick = true
	#Players respawn immediately without showing the death screen
	do_immediate_respawn = false
	#Whether phantoms can spawn in the nighttime
	do_insomnia = true
	#Whether players should be able to craft only those recipes that they've unlocked first
	do_limited_crafting = false
	#Whether mobs should drop items and experience orbs
	do_mob_loot = true
	#Whether mobs should naturally spawn. Does not affect monster spawners
	do_mob_spawning = false
	#Whether patrols can spawn
	do_patrol_spawning = true
	#Whether blocks should have drops
	do_tile_drops = true
	#Whether wandering traders can spawn
	do_trader_spawning = true
	#Whether the weather can change naturally. The /weather command can still change weather
	do_weather_cycle = true
	#Whether the player should take damage when drowning
	drowning_damage = true
	#Whether the player should take fall damage
	fall_damage = true
	#Whether the player should take damage in fire, lava, campfires, or on magma blocks
	fire_damage = true
	#Makes angered neutral mobs stop being angry when the targeted player dies nearby
	forgive_dead_players = true
	#Whether the player should take damage when inside powder snow
	freeze_damage = true
	#Whether the player should keep items and experience in their inventory after death
	keep_inventory = false
	#Whether to log admin commands to server log
	log_admin_commands = true
	#The maximum length of a chain of commands that can be executed during one tick. Applies to command blocks and functions
	#Range: > 0
	max_command_chain_length = 65536
	#The maximum number of pushable entities a mob or player can push, before taking 3 suffocation damage per half-second. Setting to 0 or lower disables the rule. Damage affects survival-mode or adventure-mode players, and all mobs but bats. Pushable entities include non-spectator-mode players, any mob except bats, as well as boats and minecarts
	#Range: > 0
	max_entity_cramming = 24
	#Whether creepers, zombies, endermen, ghasts, withers, ender dragons, rabbits, sheep, villagers, silverfish, snow golems, and end crystals should be able to change blocks and whether mobs can pick up items, which also disables bartering. This also affects the capability of zombie-like creatures like zombified piglins and drowned to pathfind to turtle eggs
	mob_griefing = true
	#Whether the player can regenerate health naturally if their hunger is full enough (doesn't affect external healing, such as golden apples, the Regeneration effect, etc.)
	natural_regeneration = true
	#What percentage of players must sleep to skip the night
	#Range: > 0
	players_sleeping_percentage = 100
	#How often a random block tick occurs (such as plant growth, leaf decay, etc.) per chunk section per game tick. 0 and negative values disables random ticks, higher numbers increase random ticks. Setting to a high integer results in high speeds of decay and growth. Numbers over 4096 make plant growth or leaf decay instantaneous
	#Range: > 0
	random_tick_speed = 3
	#Whether the debug screen shows all or reduced information; and whether the effects of F3+B (entity hitboxes) and F3+G (chunk boundaries) are shown
	reduced_debug_info = false
	#Whether the feedback from commands executed by a player should show up in chat. Also affects the default behavior of whether command blocks store their output text
	send_command_feedback = true
	#Whether death messages are put into chat when a player dies. Also affects whether a message is sent to the pet's owner when the pet dies
	show_death_messages = true
	#The number of blocks outward from the world spawn coordinates that a player spawns in when first joining a server or when dying without a personal spawnpoint
	#Range: > 0
	spawn_radius = 1
	#Whether players in spectator mode can generate chunks
	spectators_generate_chunks = true
	#Makes angered neutral mobs attack any nearby player, not just the player that angered them. Works best if forgiveDeadPlayers is disabled
	universal_anger = false

#Configs related to difficult changes
[difficulty]
	#If the difficulty should be set on world load
	#If true difficulty changes in game will also be saved to the config
	set_difficulty = true
	#The difficulty to set if 'set_difficulty' is true, respects if the difficulty is locked or not for the world
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	difficulty = "NORMAL"
	#If true the world will be set to hardcore, difficultly will be set to hard independent to the 'difficulty' config
	#Setting it to hardcore auto locks the difficulty while this is true
	hardcore = false
	#If a world's difficulty should be locked when loaded, if world already is locked it can't be changed
	#If the global world difficulty is enabled it's set first
	lock_difficulty = true

#A collection of misc configs
[misc]
	#If gamerules should be saved to config on world unload
	save_gamerules = true
	#A comma separated list of commands to run on world join, @p is replaced with joining player name, command is run by the server
	#Example: default_commands = ["/tellraw @p [\"\",{\"text\":\"Hi \"},{\"text\":\"@p\",\"color\":\"aqua\"}]"]
	default_commands = []

